#ifndef __ERRORS_H__
#define __ERRORS_H__

#define ERR_NON_INTEGER 100
#define ERR_MENU_KEY_OUT_OF_RANGE 101
#define ERR_NO_MEMORY 102
#define ERR_EMPTY_STRING 103
#define ERR_PRICE_RANGE 104
#define ERR_INPUT_STRING 105
#define ERR_INPUT_NUMBER 106
// #define ERR_STRING_TOO_LONG 107
#define ERR_MENU_KEY_INPUT 108
#define ERR_OPEN_FILE 109
#define ERR_CLOSE_FILE 110
#define ERR_FILE_BROKEN 111
#define ERR_OUT_OF_RANGE 112;
#define ERR_QUEUE_EMPTY 113;
#define ERR_QUEUE_FULL 114;
#define ERR_DOMAIN 115;
#define ERR_NOT_FOUND 116;
#define ERR_NULL_POINTER 117;

#endif // __ERRORS_H__
